name: Pull Request Validation

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint and type checking
        run: npm run lint

      - name: Run tests with coverage
        run: npm test
        env:
          CI: true

      - name: Check test coverage threshold
        run: |
          COVERAGE=$(npm test -- --coverage --coverageReporters=json-summary 2>/dev/null | grep -oP '"lines":\s*\{"total":\s*\K\d+\.\d+' || echo "0")
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 75" | bc -l) )); then
            echo "Coverage $COVERAGE% is below 75% threshold"
            exit 1
          fi

      - name: Build project
        run: npm run build

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: matrix.node-version == '20.x'
        with:
          files: ./coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  status:
    name: PR Status Check
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: Check job status
        run: |
          if [ "${{ needs.test.result }}" != "success" ]; then
            echo "Tests failed - blocking PR merge"
            exit 1
          fi
          echo "All checks passed - PR ready for review"
